import { StyleSheet } from "react-native";
import { Colors } from "../../Global/colors";
import { Fonts } from "../../Global/fonts";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  center: {
    flex: 1,
    backgroundColor: Colors.Black,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: Colors.White,
    fontSize: 16,
    fontFamily: Fonts.FONT_REGULAR,
    marginTop: 16,
  },
  overlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  processingText: {
    color: Colors.White,
    fontSize: 16,
    fontFamily: Fonts.FONT_REGULAR,
    marginTop: 16,
  },
  scanArea: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -100 }, { translateY: -100 }],
    width: 200,
    height: 200,
    alignItems: "center",
    justifyContent: "center",
  },
  scanFrame: {
    width: 200,
    height: 200,
    borderWidth: 2,
    borderColor: Colors.Primary,
    borderRadius: 8,
    backgroundColor: "transparent",
  },
  scanText: {
    color: Colors.White,
    fontSize: 14,
    fontFamily: Fonts.FONT_REGULAR,
    marginTop: 16,
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  manualInputContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.White,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderColor,
    gap: 12,
  },
  manualInput: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderColor: Colors.borderColor,
    borderRadius: 8,
    paddingHorizontal: 16,
    fontSize: 14,
    fontFamily: Fonts.FONT_REGULAR,
    color: Colors.PrimaryText,
    backgroundColor: Colors.White,
  },
  submitButton: {
    height: 44,
    paddingHorizontal: 20,
    backgroundColor: Colors.Primary,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  submitButtonDisabled: {
    backgroundColor: Colors.gray,
    opacity: 0.6,
  },
  submitButtonText: {
    fontSize: 14,
    fontFamily: Fonts.FONT_Semi,
    color: Colors.White,
  },
  actionTypeContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.White,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderColor,
    gap: 24,
  },
  actionTypeOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderWidth: 2,
    borderColor: Colors.borderColor,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.White,
  },
  checkboxChecked: {
    backgroundColor: Colors.Primary,
    borderColor: Colors.Primary,
  },
  actionTypeText: {
    fontSize: 14,
    fontFamily: Fonts.FONT_REGULAR,
    color: Colors.PrimaryText,
  },
});
